baseURL = 'https://fv-pfeffermaeuse.de/'
languageCode = 'de-DE'
title = 'Förderverein Kneipp-Kita Pfeffermäuse e.V.'
theme = 'blowfish'

enableRobotsTXT = true
paginate = 100
summaryLength = 30

# googleAnalytics = ""

[imaging]
  anchor = 'Center'

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  colorScheme = "slate" 
  defaultAppearance = "light"
  autoSwitchAppearance = "false"
  logo = "img/logo-small.jpg"
  description = "Der ehrenamtliche Förderverein Pfeffermäuse unterstützt die Kneipp-Kita Pfeffermäuse und verwirklicht tolle neue Projekte für die Kinder!"
  enableSearch = false

[params.homepage]
  layout = "hero"
  showRecent = true
  cardView = true
  cardViewScreenWidth = false
  homepageImage = "img/garten_pfeffermaeuse.jpg"

[params.footer]
  showAppearanceSwitcher = false

[[menus.main]]
  name = "Über uns"
  pageRef = "about"
  weight = 5  
[[menus.main]]
  name = "Mitgliedschaft"
  pageRef = "membership"
  weight = 10  
[[menus.main]]
  name = "Impressum"
  pageRef = "impressum"
  weight = 15  

[params.article]
  showHero = true
  showDate = false
  showDateUpdated = false
  showHeadingAnchors = false
  showPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false 
  showWordCount = false
  showSummary = false
  sharingLinks = [ "whatsapp", "reddit", "facebook", "email"]